// <auto-generated />
using System;
using Cell.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cell.Application.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190609063250_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cell.Domain.Aggregates.SettingFieldAggregate.SettingField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<int>("AllowFilter")
                        .HasColumnName("ALLOW_FILTER");

                    b.Property<int>("AllowSummary")
                        .HasColumnName("ALLOW_SUMMARY");

                    b.Property<string>("Caption")
                        .HasColumnName("CAPTION")
                        .HasMaxLength(200);

                    b.Property<string>("Code")
                        .HasColumnName("CODE");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnName("CREATED");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("Data")
                        .HasColumnName("DATA")
                        .HasColumnType("xml");

                    b.Property<string>("DataType")
                        .HasColumnName("DATA_TYPE")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTimeOffset>("Modified")
                        .HasColumnName("MODIFIED");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<string>("Name")
                        .HasColumnName("NAME");

                    b.Property<int>("OrdinalPosition")
                        .HasColumnName("ORDINAL_POSITION");

                    b.Property<string>("PlaceHolder")
                        .HasColumnName("PLACE_HOLDER")
                        .HasMaxLength(200);

                    b.Property<string>("Settings")
                        .HasColumnName("SETTINGS");

                    b.Property<string>("StorageType")
                        .HasColumnName("STORAGE_TYPE")
                        .HasMaxLength(50);

                    b.Property<Guid>("TableId")
                        .HasColumnName("TABLE_ID");

                    b.Property<string>("TableName")
                        .HasColumnName("TABLE_NAME")
                        .HasMaxLength(200);

                    b.Property<int>("Version")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.ToTable("T_SETTING_FIELD");
                });

            modelBuilder.Entity("Cell.Domain.Aggregates.SettingTableAggregate.SettingTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("BasedTable")
                        .HasColumnName("BASED_TABLE")
                        .HasMaxLength(200);

                    b.Property<string>("Code")
                        .HasColumnName("CODE");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnName("CREATED");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("Data")
                        .HasColumnName("DATA")
                        .HasColumnType("xml");

                    b.Property<string>("Description")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTimeOffset>("Modified")
                        .HasColumnName("MODIFIED");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnName("MODIFIED_BY");

                    b.Property<string>("Name")
                        .HasColumnName("NAME");

                    b.Property<string>("Settings")
                        .HasColumnName("SETTINGS");

                    b.Property<int>("Version")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.ToTable("T_SETTING_TABLE");
                });
#pragma warning restore 612, 618
        }
    }
}
